<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Dapper" Version="2.1.72" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
		<PackageReference Include="Riok.Mapperly" Version="4.3.1" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Core.Domain\Core.Domain.csproj" />
		<ProjectReference Include="..\Core.Utils\Core.Utils.csproj" />
		<PackageReference Include="CsvHelper" Version="33.1.0" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="CustomModels\INModel\" />
	  <Folder Include="Scripts\" />
	</ItemGroup>
	<ItemGroup>
	  <None Update="Scripts\backup.bat">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>
