-- Apply after access-control.sql. Existing ERP tables are not changed by this script.
CREATE TABLE IF NOT EXISTS erp_unit (
    "Code" varchar(20) PRIMARY KEY,
    "Name" varchar(150) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "SortOrder" integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS erp_plant (
    "Code" varchar(20) PRIMARY KEY,
    "UnitCode" varchar(20) NOT NULL REFERENCES erp_unit("Code"),
    "Name" varchar(150) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "SortOrder" integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS ix_erp_plant_unit ON erp_plant("UnitCode");

CREATE TABLE IF NOT EXISTS erp_user_plant (
    "UserId" integer NOT NULL,
    "PlantCode" varchar(20) NOT NULL REFERENCES erp_plant("Code"),
    PRIMARY KEY ("UserId", "PlantCode")
);

CREATE TABLE IF NOT EXISTS erp_notification (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" varchar(200) NOT NULL,
    "Body" text NOT NULL,
    "UnitCode" varchar(20),
    "PlantCode" varchar(20),
    "RecipientUserId" integer,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "ExpiresAtUtc" timestamp with time zone,
    "CreatedByUserId" integer NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_erp_notification_target ON erp_notification("UnitCode", "PlantCode", "RecipientUserId", "CreatedAtUtc");

CREATE TABLE IF NOT EXISTS erp_notification_read (
    "NotificationId" bigint NOT NULL REFERENCES erp_notification("Id") ON DELETE CASCADE,
    "UserId" integer NOT NULL,
    "ReadAtUtc" timestamp with time zone NOT NULL,
    PRIMARY KEY ("NotificationId", "UserId")
);

CREATE TABLE IF NOT EXISTS erp_setting (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Key" varchar(100) NOT NULL,
    "Value" text NOT NULL,
    "Scope" varchar(50) NOT NULL,
    "IsPublic" boolean NOT NULL DEFAULT false,
    "UpdatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedByUserId" integer NOT NULL,
    CONSTRAINT ux_erp_setting_key_scope UNIQUE ("Key", "Scope")
);
