<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Astemo.Domain\Astemo.Domain.csproj" />
		<ProjectReference Include="..\Astemo.Utils\Astemo.Utils.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="EFCore.BulkExtensions.PostgreSql" Version="6.6.5" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.25" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.25" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.25">

			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.22" />
		<PackageReference Include="System.Text.Json" Version="6.0.0" />
	</ItemGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
</Project>
