; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "PlastMB Main Service API"
#define MyAppVersion "1.0.1"
#define MyAppPublisher "FA System and Technology Vietnam Co., Ltd"
#define MyAppURL "https://fstv.vn"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{025F3907-A2BB-48A6-B4FA-25A05C68CA2C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\inetpub\wwwroot\PlastMB
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=PlastMBIISSetup-ver1.0.1
Compression=lzma
SolidCompression=yes
WizardStyle=modern
WizardImageFile="Setup\banner.bmp"
WizardSmallImageFile=Setup\logo.bmp
;UsePreviousTasks=yes

;https://github.com/jrsoftware/issrc/tree/main/Files/Languages/Unofficial
[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "vietnamese"; MessagesFile: "compiler:Languages\Unofficial\Vietnamese.isl"

[Files]
Source: "D:\PlastBm\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Thông tin cần biết về phần mềm
Source: ".\Setup\README.txt"; DestName: "README.txt"; DestDir: "{app}"; Languages: english; Flags: isreadme
Source: ".\Setup\README_jp.txt"; DestName: "README_jp.txt"; DestDir: "{app}"; Languages: japanese; Flags: isreadme
Source: ".\Setup\README_vi.txt"; DestName: "README_vi.txt"; DestDir: "{app}"; Languages: vietnamese; Flags: isreadme
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Tasks]
Name: "setupiis"; Description: "Install, Enable IIS (Internet Information Service) Manager on Windows 11"; GroupDescription: "Select installation type:"; Languages: english; Flags: exclusive
Name: "setupiis"; Description: "Windows11でIISのインストール"; GroupDescription: "インストールタイプを選択:";  Languages: japanese; Flags: exclusive
Name: "setupiis"; Description: "Cài đặt và kích hoạt IIS (Internet Information Service) Manager"; GroupDescription: "Chọn kiểu cài đặt:";  Languages: vietnamese; Flags: exclusive
Name: "setupservice"; Description: "Install PlastMB Main Service API"; GroupDescription: "Select installation type:"; Languages: english; Flags: exclusive
Name: "setupservice"; Description: "PlastMBメインサービスAPIをインストールする"; GroupDescription: "インストールタイプを選択:"; Languages: japanese; Flags: exclusive
Name: "setupservice"; Description: "Cài đặt PlastMB Main Service API"; GroupDescription: "Chọn kiểu cài đặt:"; Languages: vietnamese; Flags: exclusive

; Khi dịch vụ chạy dưới tài khoản LocalSystem, nó sẽ sử dụng thông tin đăng nhập của tài khoản máy tính để truy cập các tài nguyên chia sẻ trên mạng trong môi trường miền (Domain).

[Run]
; Publish Website On IIS Using AppCmd
; Install IIS and ASP.NET Modules
Filename: {sys}\dism.exe; Parameters: "/online /enable-feature /featurename:IIS-WebServerRole /all" ; Flags: runhidden; Tasks: setupiis; StatusMsg: "[1/1] DISM command to install IIS..."

; Register hosting or publishing a website.
Filename: {sys}\inetsrv\appcmd.exe; Parameters: "add site /name:PlastMB /bindings:""http/*:2511:"" /physicalPath:""C:\inetpub\wwwroot\PlastMB""" ; Flags: runhidden; Tasks: setupservice; StatusMsg: "[1/2] Create the WebSite in IIS using AppCMD command line..."
; Start hosting or publishing a website
Filename: {sys}\inetsrv\appcmd.exe; Parameters: "start site ""PlastMB""" ; Flags: runhidden; Tasks: setupservice; StatusMsg: "[2/2] Start main Web Server API."

[UninstallRun]
; Stop the Web Server API
Filename: {sys}\inetsrv\appcmd.exe; Parameters: "stop site ""PlastMB""" ; Flags: runhidden;
; Delete or remove published or hosted websites from IIS
Filename: {sys}\inetsrv\appcmd.exe; Parameters: "delete site ""PlastMB""" ; Flags: runhidden;

; Disable when don’t require the IIS Modules anymore
;Filename: {sys}\dism.exe; Parameters: "/online /disable-feature /featurename:IIS-WebServerRole /remove /norestart" ; Flags: runhidden; Tasks: setupiis;