; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "PlastMB Service Worker"
#define MyAppVersion "1.0.1"
#define MyAppPublisher "FA System and Technology Vietnam Co., Ltd"
#define MyAppURL "https://fstv.vn"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8AA1D4C4-A693-4AE8-AD9A-52640EE99FC1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\Public\PlastMB
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=PlastMBServiceWorkerSetup-ver1.0.1
Compression=lzma
SolidCompression=yes
WizardStyle=modern
WizardImageFile="Setup\banner.bmp"
WizardSmallImageFile=Setup\logo.bmp
;UsePreviousTasks=yes

;https://github.com/jrsoftware/issrc/tree/main/Files/Languages/Unofficial
[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "vietnamese"; MessagesFile: "compiler:Languages\Unofficial\Vietnamese.isl"

[Files]
Source: "D:\RobotcomFa\06 - FAP2501\FAP2501\PlastMB\PlastMB.WorkerService\bin\Release\net8.0\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Thông tin cần biết về phần mềm
Source: ".\Setup\README.txt"; DestName: "README.txt"; DestDir: "{app}"; Languages: english; Flags: isreadme
Source: ".\Setup\README_jp.txt"; DestName: "README_jp.txt"; DestDir: "{app}"; Languages: japanese; Flags: isreadme
Source: ".\Setup\README_vi.txt"; DestName: "README_vi.txt"; DestDir: "{app}"; Languages: vietnamese; Flags: isreadme
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Tasks]
;Name: "addnewuser"; Description: "Create a new Windows user account for this service"; GroupDescription: "Select installation type:"; Languages: english; Flags: exclusive
;Name: "addnewuser"; Description: "このサービス用に新しいWindowsユーザーアカウントを作成します"; GroupDescription: "インストールタイプを選択:";  Languages: japanese; Flags: exclusive
;Name: "addnewuser"; Description: "Tạo tài khoản người dùng Windows mới cho dịch vụ này"; GroupDescription: "Chọn kiểu cài đặt:";  Languages: vietnamese; Flags: exclusive
Name: "setupservice"; Description: "Install PlastMB Service Worker"; GroupDescription: "Select installation type:"; Languages: english; Flags: exclusive
Name: "setupservice"; Description: "PlastMBバッテリーサービスワーカーのインストール"; GroupDescription: "インストールタイプを選択:"; Languages: japanese; Flags: exclusive
Name: "setupservice"; Description: "Cài đặt dịch vụ PlastMB Service Worker"; GroupDescription: "Chọn kiểu cài đặt:"; Languages: vietnamese; Flags: exclusive

; Khi dịch vụ chạy dưới tài khoản LocalSystem, nó sẽ sử dụng thông tin đăng nhập của tài khoản máy tính để truy cập các tài nguyên chia sẻ trên mạng trong môi trường miền (Domain).

[Run]
; Create a new user for the service
;Filename: {sys}\cmd.exe; Parameters: "/C net user PlastMBService 833555 /add" ; Flags: runhidden; Tasks: addnewuser; StatusMsg: "[1/7] Create a new user for the service..."
; Add the user to the Administrators group
;Filename: {sys}\cmd.exe; Parameters: "/C net localgroup Administrators PlastMBService /add"; Flags: runhidden; StatusMsg: "[2/8] Adding user to Administrators group..."

; Register the service.
Filename: {sys}\sc.exe; Parameters: "create PlastMBServiceWorker binPath= ""C:\Public\PlastMB\PlastMB.WorkerService.exe""" ; Flags: runhidden; Tasks: setupservice; StatusMsg: "[1/5] Register the service..."
; Configure the names of the service.
Filename: {sys}\sc.exe; Parameters: "config PlastMBServiceWorker displayname=""PlastMB Service Worker""" ; Flags: runhidden; Tasks: setupservice; StatusMsg: "[2/5] Configure the names of the service..."
; Add the description to the service.
Filename: {sys}\sc.exe; Parameters: "description PlastMBServiceWorker ""Import .dat file into DataBase""" ; Flags: runhidden; Tasks: setupservice; StatusMsg: "[3/5] Add the description to the service..."
; Configure specify delayed auto start.
Filename: {sys}\sc.exe; Parameters: "config PlastMBServiceWorker start= auto" ; Flags: runhidden; Tasks: setupservice; StatusMsg: "[4/5] Configure specify auto start..."
; Change the service account
;Filename: {sys}\sc.exe; Parameters: "config PlastMBServiceWorker obj= "".\PlastMBService"" password= ""833555""" ; Flags: runhidden; Tasks: setupservice; StatusMsg: "[5/5] Change the service account..."
; Start the service
Filename: {sys}\sc.exe; Parameters: "start PlastMBServiceWorker" ; Flags: runhidden; Tasks: setupservice; StatusMsg: "[5/5] Start the service."

[UninstallRun]
; Stop the service
Filename: {sys}\sc.exe; Parameters: "stop PlastMBServiceWorker" ; Flags: runhidden;
; Delete the service
Filename: {sys}\sc.exe; Parameters: "delete PlastMBServiceWorker" ; Flags: runhidden;