
"DateManufacture" timestamp with time zone,
"DateManufacture" timestamp without time zone,

-----------------------------------

SELECT "HUCode", Count("HUCode") FROM public.ecu_data
Group by "HUCode"
Having Count("HUCode")> 1

-----------------------------------

DELETE FROM public.ecu_data
Where "EcuDataID" IN (
SELECT "EcuDataID"
FROM
    (SELECT "EcuDataID",ROW_NUMBER() OVER (PARTITION BY "HUCode" ORDER BY "HUCode") AS RN
    FROM public.ecu_data Where "Result" = 1) t Where t.RN > 1
)

----------

DELETE FROM public.ecu_data where "DateManufacture" < '2024-03-01'

SELECT * FROM public.ecu_data
Where "DateManufacture" < '2024-03-01'
ORDER BY "EcuDataID" DESC LIMIT 1000

-----------------------------------

CREATE TABLE IF NOT EXISTS public.ecu_exported
(
    "EcuDataID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "DateManufacture" timestamp without time zone,
    "NgCode" character varying(10) COLLATE pg_catalog."default",
    "Note" character varying(200) COLLATE pg_catalog."default",
    "Result" integer NOT NULL,
    "HUCode" character varying(20) COLLATE pg_catalog."default",
    "LaserPrinting" character varying(30) COLLATE pg_catalog."default",
    "ValidFlg" integer NOT NULL,
    "CreateTime" character varying(14) COLLATE pg_catalog."default",
    "CreateId" character varying(5) COLLATE pg_catalog."default",
    "UpdateTime" character varying(14) COLLATE pg_catalog."default",
    "UpdateId" character varying(5) COLLATE pg_catalog."default",
    "PackState" integer DEFAULT 0,
    CONSTRAINT "PK_ecu_exported" PRIMARY KEY ("EcuDataID")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.ecu_exported
    OWNER to postgres;